name: Windows

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install dependencies
        run: |
          pip install conan
          conan config set general.revisions_enabled=1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure -- Release
        run: cmake -S . -B cmake-build-release -G "Visual Studio 16 2019" -D CMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release --config "Release"

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release
